### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by yhkaplan** [yhkaplan/Reg#1]
- [x] Tests for operators
- [ ] README
- [ ] Capture groups (https://samwize.com/2016/07/21/how-to-capture-multiple-groups-in-a-regex-with-swift/)
- [ ] Replacement (https://nshipster.com/nsregularexpression/)
- [ ] Built in wrapper for NSDataDetector with additions like email? https://nshipster.com/nsdatadetector/
> Currently the NSDataDetector class can match dates, addresses, links, phone numbers and transit information.

**Comment by yhkaplan** [comment]
Current coverage

<img width="535" alt="2019-01-29 13 52 14" src="https://user-images.githubusercontent.com/25879490/51885070-54d4a280-23cd-11e9-8eb2-f86835bf2cd0.png">
